install.packages("tidyverse")
install.packages("readxl")
install.packages("knitr")
install.packages("ggplot2")
install.packages("lubridate")
install.packages("arules")
install.packages("arulesViz")
install.packages("dplyr")
install.packages("plyr")
library(tidyverse)
library(readxl)
library(knitr)
library(ggplot2)
library(lubridate)
library(arules)
library(arulesViz)
library(plyr)
library(readxl)
retail <- read_excel("Online Retail.xlsx")
View(retail)

retail <- retail[complete.cases(retail), ]
retail % mutate(Description = as.factor(Description))
library(dplyr)
retail % mutate(Description = as.factor(Description))
library(tibble)
retail<-as_data_frame(retail)
retail % mutate(Description = as.factor(Description))
mutate(Description_1 = as.factor(Description))
mutate(retail,Description_1 = as.factor(Description))
View(retail)
retail %% mutate(retail,Description_1 = as.factor(Description))
retail % mutate(retail,Description_1 = as.factor(Description))
retail %>% mutate(retail,Description_1 = as.factor(Description))
View(retail)
glimpse(retail)

retail$Description<-as.factor(retail$Description)
retail$Country<-as.factor(retail$Country)

glimpse(retail)
retail$Date<-as.Date(retail$InvoiceDate)
retail$time<-format(retail$InvoiceDate, "%H:%M:%S")
retail$InvoiceNo<-as.numeric(as.character(retail$InvoiceNo))
glimpse
glimpse(retail)
retail_sorted <- retail[order(retail$CustomerID),]
library(plyr)
itemList <- ddply(retail,c("CustomerID","Date"),
function(df1)paste(df1$Description,
collapse = ","))
View(itemList)
itemList$CustomerID <- NULL
itemList$Date <- NULL
colnames(itemList) <- c("items")
write.csv(itemList,"market_basket.csv", quote = FALSE, row.names = TRUE)
tr <- read.transactions('market_basket.csv', format = 'basket', sep=',')
itemFrequencyPlot(tr, topN=20, type='absolute')
rules <- apriori(tr, parameter = list(supp=0.001, conf=0.8))
rules <- sort(rules, by='confidence', decreasing = TRUE)
summary(rules)
inspect(rules[1:10])
topRules <- rules[1:10]
plot(topRules)
plot(topRules, method="graph")
